
# **Mastering Numpy library** _Day 03_

##### Name: Muhammad Hassaan
##### Date: Jan 28, 2024
##### Email: muhammadhassaan7896@gmail.com

## Numpy Indexing and Slicing

In [2]:
import pandas as pd 
import numpy as np

In [3]:
# create a numpy array 
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
a[-1]

10

In [7]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [8]:
b[2:]

array([ 4,  6,  8, 10])

In [19]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [18]:
c[0:1]

array([[0, 2]])

In [20]:
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [26]:
c[(c < 5)]

array([0, 2, 4])

## Enlist booleans operators conditional operators 

Certainly! Here's a table of Python conditional operators (comparison operators) and boolean operators along with their functions and definitions:

| Operator | Function | Definition |
|----------|----------|------------|
| ==       | Equal    | Returns True if the values on both sides are equal. |
| !=       | Not Equal | Returns True if the values on both sides are not equal. |
| <        | Less Than | Returns True if the value on the left is less than the value on the right. |
| >        | Greater Than | Returns True if the value on the left is greater than the value on the right. |
| <=       | Less Than or Equal To | Returns True if the value on the left is less than or equal to the value on the right. |
| >=       | Greater Than or Equal To | Returns True if the value on the left is greater than or equal to the value on the right. |

Boolean operators are used to perform operations on boolean values (True or False).

| Operator | Function | Definition |
|----------|----------|------------|
| and      | Logical AND | Returns True if both conditions on the left and right are True. Otherwise, it returns False. |
| or       | Logical OR | Returns True if at least one of the conditions on the left or right is True. If both are False, it returns False. |
| not      | Logical NOT | Returns True if the condition is False and vice versa. It negates the boolean value. |

Example usage:

```python
# Conditional operators
x = 5
y = 10

print(x == y)  # False
print(x < y)   # True
print(x >= y)  # False

# Boolean operators
a = True
b = False

print(a and b)  # False
print(a or b)   # True
print(not a)    # False
```

These operators are fundamental in creating logical conditions in Python programs.