
# **Mastering Numpy library** _Day 02_

##### Name: Muhammad Hassaan
##### Date: Jan 28, 2024
##### Email: muhammadhassaan7896@gmail.com

In [2]:
# import libraries 
import pandas as pd
import numpy as np

In [13]:
# empty array 
empty = np.empty((2, 5))
print(empty)

[[5.81848703e+180 1.46923448e+195 5.98183374e-154 6.01347002e-154
  6.10904875e+223]
 [3.09540936e+169 6.62277974e+265 2.03386010e+233 9.08367229e+223
  5.73568013e+169]]


In [14]:
empty[0] # printing index

array([5.81848703e+180, 1.46923448e+195, 5.98183374e-154, 6.01347002e-154,
       6.10904875e+223])

In [20]:
x = np.arange(0, 100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
even = np.arange(0, 100, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
# array of odd numbers
odd = np.arange(1, 100, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
# specific difference 
diff = np.arange(0, 100, 3)
diff

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [41]:
# lin space 
lin = np.linspace(0, 10, num=17)
lin

array([ 0.   ,  0.625,  1.25 ,  1.875,  2.5  ,  3.125,  3.75 ,  4.375,
        5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   ])

In [42]:
lin.dtype

dtype('float64')

In [45]:
# define the data type of th array 
x = np.arange(0, 100, 1.5, dtype=np.float64)
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5, 30. , 31.5,
       33. , 34.5, 36. , 37.5, 39. , 40.5, 42. , 43.5, 45. , 46.5, 48. ,
       49.5, 51. , 52.5, 54. , 55.5, 57. , 58.5, 60. , 61.5, 63. , 64.5,
       66. , 67.5, 69. , 70.5, 72. , 73.5, 75. , 76.5, 78. , 79.5, 81. ,
       82.5, 84. , 85.5, 87. , 88.5, 90. , 91.5, 93. , 94.5, 96. , 97.5,
       99. ])

## **Assisgnment: What is the difference between int(8, 16, 32, 64, 128, 256), and float(8, 16, 32, 64, 128, 256)? and why we sue one and not the other one?**

The main difference between int(8, 16, 32, 64, 128, 256) and float(8, 16, 32, 64, 128, 256) lies in the way they represent numbers and the operations they support.

int(8, 16, 32, 64, 128, 256): These are integer data types. Integers are whole numbers, positive or negative, without decimals, that can be used for counting, indexing, etc. The numbers in parentheses represent the number of bits used to represent the integer. For example, int8 can represent integers from -128 to 127, int16 from -32,768 to 32,767, and so on. The choice between different integer types depends on the range of numbers you need to represent and the amount of memory you want to use.

float(8, 16, 32, 64, 128, 256): These are floating-point data types. Floating-point numbers are numbers that have a decimal point or a fractional component. The numbers in parentheses represent the number of bits used to represent the floating-point number. For example, float32 can represent approximately 7 decimal digits, while float64 can represent approximately 15 decimal digits. The choice between different floating-point types depends on the precision and range of numbers you need to represent and the amount of memory and computational resources you want to use.

In general, you would use integers when you need to represent whole numbers, counts, or indices, and floating-point numbers when you need to represent real numbers with a fractional component or a large range of values. The choice between one and the other would depend on the specific requirements of your program or algorithm.


In [46]:
# sorting 
arr = np.array([13,45,6,5,7,67,67,2])
arr

array([13, 45,  6,  5,  7, 67, 67,  2])

In [47]:
arr = np.sort(arr)
arr

array([ 2,  5,  6,  7, 13, 45, 67, 67])

In [52]:
# concatenate
a = np.array([1,3, 5, 7, 9])
b = np.array([2,4, 6, 8, 10])

x = np.concatenate((a, b))
x

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [54]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
w = np.array([[5, 1], [3, 4]])
x = np.array([[1, 2], [3, 4]])

z1 = np.concatenate((w, x), axis = 1)
z1

array([[5, 1, 1, 2],
       [3, 4, 3, 4]])

In [57]:
x.ndim

2

In [58]:
y.ndim

2

In [60]:
# 3d array 
array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [61]:
array.ndim

3

In [62]:
len(array)

3

In [63]:
array.size

24

In [64]:
array.dtype

dtype('int32')

In [65]:
array.shape

(3, 2, 4)

In [67]:
# create a 3d array of size(3, 1, 4)
array_1 = np.array([[[0, 1, 2, 3]],
                    [[0, 11, 23, 34]],
                    [[0 ,12 ,42, 32]]])
array_1

array([[[ 0,  1,  2,  3]],

       [[ 0, 11, 23, 34]],

       [[ 0, 12, 42, 32]]])

In [68]:
array_1.shape

(3, 1, 4)

In [69]:
array_1.size

12

In [70]:
a

array([1, 3, 5, 7, 9])

In [77]:
a =  np.array([[[0, 1, 2, 3]],
                    [[0, 11, 23, 34]],
                    [[0 ,12 ,42, 32]]])
a.shape

(3, 1, 4)

In [78]:
a2 = a.reshape(6, 2)
a2.shape

(6, 2)

In [79]:
a2

array([[ 0,  1],
       [ 2,  3],
       [ 0, 11],
       [23, 34],
       [ 0, 12],
       [42, 32]])

1d to 3d 


In [81]:
# converting 1 d array into 2d array 
a = np.array([1, 3, 5, 7, 9])
a.shape

(5,)

In [82]:
a2 = a[np.newaxis, :]
a2.shape

(1, 5)

In [83]:
a2

array([[1, 3, 5, 7, 9]])

## Indexing and scaling 

In [85]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [87]:
print(data[1], data[0:2], data[1:], data[-2:])

2 [1 2] [2 3] [2 3]


In [89]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
print(a[a < 5])

[1 2 3 4]


In [92]:
a[a % 2 == 0] # filtering

array([ 2,  4,  6,  8, 10, 12])

In [101]:
# use two conditions 
a[(a>2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
a[(a>2) | (a > 11) ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])