
# **Mastering Numpy library** _Day 01_

##### Name: Muhammad Hassaan
##### Date: Jan 28, 2024
##### Email: muhammadhassaan7896@gmail.com

In [59]:
# import libraries
import pandas as pd 
import numpy as np 
import random

What is an array?

An array is a data structure that stores a collection of elements, each identified by its index. The index of the first element in an array is always 0, and the index of the last element is the size of the array minus one. Arrays are useful when you need to store multiple values of the same type together, such as a list of numbers or a set of names.

In [60]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [61]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [62]:
a3 = a[:, np.newaxis]
print(a3.shape)
a3

(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

---
# **Why do we have 1d, 2d and 3d arrays and where we need them in Data Science?**

In Data Science, arrays are used to store and manipulate data. The dimensionality of an array refers to the number of indices required to access a specific element.

1D arrays, also known as one-dimensional arrays, are the simplest form of arrays. They are used to store a collection of elements of the same data type, with each element being accessed using a single index. For example, a 1D array can be used to store the grades of a single student in multiple subjects.

2D arrays, also known as two-dimensional arrays, are used to store data in a tabular format, with rows and columns. They are accessed using two indices, one for the row and one for the column. For example, a 2D array can be used to store the grades of multiple students in multiple subjects, with each row representing a student and each column representing a subject.

3D arrays, also known as three-dimensional arrays, are used to store data in a more complex format, with three indices required to access a specific element. They can be thought of as a cube, with each cell in the cube representing a unique data point. For example, a 3D array can be used to store the grades of multiple students in multiple subjects over multiple years.

In summary, the dimensionality of an array is determined by the number of indices required to access a specific element. 1D arrays are used for simple data collections, 2D arrays are used for tabular data, and 3D arrays are used for more complex data structures. The choice of array dimensionality depends on the specific use case and the structure of the data being stored.

---

## Creating a numpy array

In [63]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3, 4, 5, 6], [4, 5, 6, 7,8, 9]])

In [64]:
type(a) # type of array

numpy.ndarray

In [65]:
a.dtype # data type of array elemnts

dtype('int32')

In [66]:
a.shape

(6,)

In [67]:
b.shape

(2, 6)

In [68]:
print(a)

[1 2 3 4 5 6]


In [69]:
print(b)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


## Initialize arrays

In [70]:
zeros = np.zeros((3, 4)) # (rows, columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
zeros.dtype

dtype('float64')

In [72]:
ones = np.ones((5, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
full = np.full((12, 13), fill_value=np.random.rand())
full

array([[0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018],
       [0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018],
       [0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018],
       [0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018],
       [0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450018, 0.77450018],
       [0.77450018, 0.77450018, 0.77450018, 0.77450018, 0.77450018,
        0.77450018, 0.77450

In [74]:
full_1 = np.full((12, 13), 7)
full_1

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [75]:
full_1.dtype

dtype('int32')

In [76]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array Attributes

In [77]:
a.shape

(6,)

In [82]:
a

array([1, 2, 3, 4, 5, 6])

In [86]:
len(a) # give us the length of array

6

In [83]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [84]:
len(b)

2

In [79]:
a.ndim # give us the dimension of array 

1

In [80]:
b.ndim

2

In [81]:
a.size # give us the size of the array

6

In [85]:
b.size

12

# Basic Operations


In [88]:
a

array([1, 2, 3, 4, 5, 6])

In [89]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [87]:
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3]])

In [91]:
h = a + b
a

array([1, 2, 3, 4, 5, 6])

In [93]:
h1 = np.add(a, b) # another method
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [94]:
# division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667]])

In [95]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36])