
# **Mastering Numpy library** _Day 04_

##### Name: Muhammad Hassaan
##### Date: Jan 28, 2024
##### Email: muhammadhassaan7896@gmail.com

In [1]:
import pandas as pd
import numpy as np 

In [3]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
len(a)

10

In [4]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [7]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [9]:
c = np.vstack((a1, a2))
c

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])